def generate_sales_report(summary):

    report = f"""
InsightForge AI

Sales Intelligence Report

--------------------------------

{summary}

--------------------------------

Generated by InsightForge AI
"""

    return report


def generate_finance_report(summary):

    report = f"""
InsightForge AI

Finance Intelligence Report

--------------------------------

{summary}

--------------------------------

Generated by InsightForge AI
"""

    return report


def generate_hr_report(summary):

    report = f"""
InsightForge AI

HR Intelligence Report

--------------------------------

{summary}

--------------------------------

Generated by InsightForge AI
"""

    return report


def generate_marketing_report(summary):

    report = f"""
InsightForge AI

Marketing Intelligence Report

--------------------------------

{summary}

--------------------------------

Generated by InsightForge AI
"""

    return report